name: 'Install npm modules'
description: 'Runs npm install for multiple paths with steps enabled via inputs'

inputs:
  root:
    description: 'Enable npm install for ./'
    required: false
    default: false

  source:
    description: 'Enable npm install for ./source/'
    required: false
    default: false

  scripts:
    description: 'Enable npm install for ./source/scripts/'
    required: false
    default: false

  website:
    description: 'Enable npm install for ./source/website/'
    required: false
    default: false

  discord:
    description: 'Enable npm install for ./source/scripts/discord/'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Install npm modules for ./
      if: (inputs.root == 'true' || inputs.source == 'true' || inputs.website == 'true' || inputs.scripts == 'true' || inputs.discord == 'true')
      uses: ./.github/actions/npm-install
      with:
        working-directory: ''

    - name: Install npm modules for ./source/
      if: (inputs.source == 'true' || inputs.website == 'true' || inputs.scripts == 'true' || inputs.discord == 'true')
      uses: ./.github/actions/npm-install
      with:
        working-directory: 'source/'

    - name: Install npm modules for ./source/website/
      if: (inputs.website == 'true')
      uses: ./.github/actions/npm-install
      with:
        working-directory: 'source/website/'

    - name: Install npm modules for ./source/scripts/
      if: (inputs.scripts == 'true' || inputs.discord == 'true')
      uses: ./.github/actions/npm-install
      with:
        working-directory: 'source/scripts/'

    - name: Install npm modules for ./source/scripts/discord/
      if: (inputs.discord == 'true')
      uses: ./.github/actions/npm-install
      with:
        working-directory: 'source/scripts/discord/'
