# Simple workflow for deploying static content to GitHub Pages
name: Update mods from known repos

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "24 * * * *"

# Sets permissions of the GITHUB_TOKEN to allow push and requesting PRs
concurrency:
  group: update-mods-${{ github.ref }}

jobs:
  # Single deploy job since we're just deploying
  update-mods:
    runs-on: ubuntu-latest
    outputs:
      mod-urls: ${{ steps.get-urls.outputs.urls }}

    permissions:
      contents: read
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm modules
        run: |
          (cd source/scripts && npm install)

      - name: Update the mods from known repos.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd source/scripts
          npx tsx ./update-mods.ts 2>&1

      - name: Get URLs for new mods
        id: get-urls
        run: |
          echo "urls=$(npx tsx ./get-new-mod-urls.ts | jq -R -s 'split("\n") | map(select(length > 0))')" | tee -a "GITHUB_OUTPUT"

  process-urls:
    needs: update-mods
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    strategy:
      matrix:
        url: ${{ fromJson(needs.update-mods.outputs.mod-urls) }}
      
    steps:
      - name: Run import workflow for new mods
        run: |
          set +x
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"ref\":\"${{ github.ref }}\",\"inputs\":{\"url\":$(echo -n "${{ matrix.url }}" | jq -R -s)}}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/import-mods.yml/dispatches
            
